import { readFile } from "node:fs/promises";
import path from "node:path";

import { SOUND_PACK_EFFECT_CUES, SOUND_PACK_IDS } from "@/game/sound-packs";

/** Every sound pack ships the same file names, so the audio half of the
 * allowlist is expanded from the pack and cue lists rather than hand-listed. */
const audioFiles: Record<string, string> = Object.fromEntries(
  SOUND_PACK_IDS.flatMap((packId) =>
    ["gameplay_loop", "boss_loop", ...SOUND_PACK_EFFECT_CUES].map((file) => [
      `audio/${packId}/${file}.wav`,
      path.resolve(process.cwd(), `../game/audio/${packId}/${file}.wav`),
    ]),
  ),
);

const assetFiles: Record<string, string> = {
  ...audioFiles,
  "backgrounds/background_neutral_green_hills_castle_far_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_neutral_green_hills_castle_far_01.png"),
  "backgrounds/background_neutral_green_hills_foliage_near_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_neutral_green_hills_foliage_near_01.png"),
  "backgrounds/background_neutral_green_hills_waterfalls_mid_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_neutral_green_hills_waterfalls_mid_01.png"),
  "backgrounds/background_space_stars_far_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_space_stars_far_01.png"),
  "backgrounds/background_space_moon_mid_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_space_moon_mid_01.png"),
  "backgrounds/background_space_station_near_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_space_station_near_01.png"),
  "backgrounds/background_haunted_graveyard_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_haunted_graveyard_01.png"),
  "backgrounds/background_dragons_ash_far_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_dragons_ash_far_01.png"),
  "backgrounds/background_dragons_volcano_mid_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_dragons_volcano_mid_01.png"),
  "backgrounds/background_dragons_ruins_near_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_dragons_ruins_near_01.png"),
  "backgrounds/background_ice_world_mountains_far_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_ice_world_mountains_far_01.png"),
  "backgrounds/background_ice_world_glaciers_mid_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_ice_world_glaciers_mid_01.png"),
  "backgrounds/background_ice_world_crystals_near_01.png": path.resolve(process.cwd(), "../game/backgrounds/background_ice_world_crystals_near_01.png"),
  "sprites/short_sword_v1.png": path.resolve(process.cwd(), "../game/sprites/short_sword_v1.png"),
  "sprites/space_cooper_01.png": path.resolve(process.cwd(), "../game/sprites/space_cooper_01.png"),
  "sprites/space_cooper_01_attack.png": path.resolve(process.cwd(), "../game/sprites/space_cooper_01_attack.png"),
  "sprites/space_cooper_01_defeated.png": path.resolve(process.cwd(), "../game/sprites/space_cooper_01_defeated.png"),
  "sprites/space_human_01_attack.png": path.resolve(process.cwd(), "../game/sprites/space_human_01_attack.png"),
  "sprites/space_human_01_defeated.png": path.resolve(process.cwd(), "../game/sprites/space_human_01_defeated.png"),
  "sprites/space_ghost_01_defeated.png": path.resolve(process.cwd(), "../game/sprites/space_ghost_01_defeated.png"),
  "sprites/space_robot_01_defeated.png": path.resolve(process.cwd(), "../game/sprites/space_robot_01_defeated.png"),
  "sprites/neutral_human_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_human_01.png"),
  "sprites/neutral_girl_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_girl_01.png"),
  "sprites/neutral_ghost_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_ghost_01.png"),
  "sprites/neutral_cooper_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_cooper_01.png"),
  "sprites/haunted_cooper_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_cooper_01.png"),
  "sprites/haunted_human_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_human_01.png"),
  "sprites/haunted_girl_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_girl_01.png"),
  "sprites/haunted_ghost_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_ghost_01.png"),
  "sprites/haunted_robot_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_robot_01.png"),
  "sprites/space_human_01.png": path.resolve(process.cwd(), "../game/sprites/space_human_01.png"),
  "sprites/space_girl_01.png": path.resolve(process.cwd(), "../game/sprites/space_girl_01.png"),
  "sprites/dragon_cooper_01.png": path.resolve(process.cwd(), "../game/sprites/dragon_cooper_01.png"),
  "sprites/dragon_human_01.png": path.resolve(process.cwd(), "../game/sprites/dragon_human_01.png"),
  "sprites/dragon_girl_01.png": path.resolve(process.cwd(), "../game/sprites/dragon_girl_01.png"),
  "sprites/neutral_green_hills_maze_floor_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_maze_floor_01.png"),
  "sprites/neutral_green_hills_maze_wall_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_maze_wall_01.png"),
  "sprites/neutral_green_hills_maze_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_maze_obstacle_01.png"),
  "sprites/neutral_green_hills_maze_key_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_maze_key_01.png"),
  "sprites/neutral_green_hills_maze_door_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_maze_door_01.png"),
  "sprites/haunted_graveyard_maze_floor_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_maze_floor_01.png"),
  "sprites/haunted_graveyard_maze_wall_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_maze_wall_01.png"),
  "sprites/haunted_graveyard_maze_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_maze_obstacle_01.png"),
  "sprites/haunted_graveyard_maze_key_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_maze_key_01.png"),
  "sprites/haunted_graveyard_maze_door_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_maze_door_01.png"),
  "sprites/space_maze_floor_01.png": path.resolve(process.cwd(), "../game/sprites/space_maze_floor_01.png"),
  "sprites/space_maze_wall_01.png": path.resolve(process.cwd(), "../game/sprites/space_maze_wall_01.png"),
  "sprites/space_maze_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/space_maze_obstacle_01.png"),
  "sprites/space_maze_key_01.png": path.resolve(process.cwd(), "../game/sprites/space_maze_key_01.png"),
  "sprites/space_maze_door_01.png": path.resolve(process.cwd(), "../game/sprites/space_maze_door_01.png"),
  "sprites/dragons_emberkeep_maze_floor_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_maze_floor_01.png"),
  "sprites/dragons_emberkeep_maze_wall_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_maze_wall_01.png"),
  "sprites/dragons_emberkeep_maze_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_maze_obstacle_01.png"),
  "sprites/dragons_emberkeep_maze_key_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_maze_key_01.png"),
  "sprites/dragons_emberkeep_maze_door_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_maze_door_01.png"),
  "sprites/shared_hole_hazard_01.png": path.resolve(process.cwd(), "../game/sprites/shared_hole_hazard_01.png"),
  "sprites/neutral_green_hills_boss_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_boss_01.png"),
  "sprites/neutral_green_hills_flying_cooper_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_flying_cooper_01.png"),
  "sprites/neutral_green_hills_platformer_ground_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_platformer_ground_01.png"),
  "sprites/neutral_green_hills_platformer_hazard_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_platformer_hazard_01.png"),
  "sprites/neutral_green_hills_platformer_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_platformer_obstacle_01.png"),
  "sprites/neutral_green_hills_platformer_platform_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_green_hills_platformer_platform_01.png"),
  "sprites/neutral_robot_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_robot_01.png"),
  "sprites/neutral_zombie_01.png": path.resolve(process.cwd(), "../game/sprites/neutral_zombie_01.png"),
  "sprites/space_platformer_ground_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_ground_01.png"),
  "sprites/space_platformer_platform_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_platform_01.png"),
  "sprites/space_platformer_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_obstacle_01.png"),
  "sprites/space_platformer_hazard_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_hazard_01.png"),
  "sprites/space_ghost_01.png": path.resolve(process.cwd(), "../game/sprites/space_ghost_01.png"),
  "sprites/space_robot_01.png": path.resolve(process.cwd(), "../game/sprites/space_robot_01.png"),
  "sprites/space_boss_01.png": path.resolve(process.cwd(), "../game/sprites/space_boss_01.png"),
  "sprites/haunted_graveyard_platformer_ground_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_platformer_ground_01.png"),
  "sprites/haunted_graveyard_platformer_platform_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_platformer_platform_01.png"),
  "sprites/haunted_graveyard_platformer_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_platformer_obstacle_01.png"),
  "sprites/haunted_graveyard_platformer_hazard_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_platformer_hazard_01.png"),
  "sprites/haunted_graveyard_platformer_spring_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_platformer_spring_01.png"),
  "sprites/haunted_graveyard_platformer_spring_01_compressed.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_platformer_spring_01_compressed.png"),
  "sprites/haunted_tombstone_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_tombstone_01.png"),
  "sprites/haunted_spirit_orb_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_spirit_orb_01.png"),
  "sprites/haunted_boss_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_boss_01.png"),
  "sprites/haunted_flying_cooper_bat_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_flying_cooper_bat_01.png"),
  "sprites/haunted_graveyard_flaming_pumpkin_01.png": path.resolve(process.cwd(), "../game/sprites/haunted_graveyard_flaming_pumpkin_01.png"),
  "sprites/dragons_emberkeep_platformer_ground_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_platformer_ground_01.png"),
  "sprites/dragons_emberkeep_platformer_platform_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_platformer_platform_01.png"),
  "sprites/dragons_emberkeep_platformer_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_platformer_obstacle_01.png"),
  "sprites/dragons_emberkeep_platformer_hazard_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_platformer_hazard_01.png"),
  "sprites/dragons_emberkeep_platformer_coin_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_platformer_coin_01.png"),
  "sprites/dragons_emberkeep_platformer_coin_01_collected.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_platformer_coin_01_collected.png"),
  "sprites/dragons_emberkeep_platformer_checkpoint_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_platformer_checkpoint_01.png"),
  "sprites/dragons_emberkeep_platformer_goal_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_platformer_goal_01.png"),
  "sprites/dragon_ghost_01.png": path.resolve(process.cwd(), "../game/sprites/dragon_ghost_01.png"),
  "sprites/dragon_dragon_01.png": path.resolve(process.cwd(), "../game/sprites/dragon_dragon_01.png"),
  "sprites/dragons_emberkeep_fireball_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_fireball_01.png"),
  "sprites/dragons_emberkeep_flying_fireball_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_flying_fireball_01.png"),
  "sprites/dragons_emberkeep_boss_01.png": path.resolve(process.cwd(), "../game/sprites/dragons_emberkeep_boss_01.png"),
  "sprites/ice_world_platformer_ground_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_platformer_ground_01.png"),
  "sprites/ice_world_platformer_platform_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_platformer_platform_01.png"),
  "sprites/ice_world_platformer_obstacle_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_platformer_obstacle_01.png"),
  "sprites/ice_world_platformer_hazard_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_platformer_hazard_01.png"),
  "sprites/ice_world_platformer_coin_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_platformer_coin_01.png"),
  "sprites/ice_world_platformer_coin_01_collected.png": path.resolve(process.cwd(), "../game/sprites/ice_world_platformer_coin_01_collected.png"),
  "sprites/ice_world_platformer_spring_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_platformer_spring_01.png"),
  "sprites/ice_world_platformer_spring_01_compressed.png": path.resolve(process.cwd(), "../game/sprites/ice_world_platformer_spring_01_compressed.png"),
  "sprites/ice_world_cooper_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_cooper_01.png"),
  "sprites/ice_world_human_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_human_01.png"),
  "sprites/ice_world_girl_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_girl_01.png"),
  "sprites/ice_world_ghost_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_ghost_01.png"),
  "sprites/ice_world_robot_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_robot_01.png"),
  "sprites/ice_world_boss_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_boss_01.png"),
  "sprites/ice_world_boss_01_defeated.png": path.resolve(process.cwd(), "../game/sprites/ice_world_boss_01_defeated.png"),
  "sprites/ice_world_crystal_projectile_01.png": path.resolve(process.cwd(), "../game/sprites/ice_world_crystal_projectile_01.png"),
  "sprites/shared_game_over_01.png": path.resolve(process.cwd(), "../game/sprites/shared_game_over_01.png"),
  "sprites/shared_victory_burst_01.png": path.resolve(process.cwd(), "../game/sprites/shared_victory_burst_01.png"),
  "sprites/space_platformer_checkpoint_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_checkpoint_01.png"),
  "sprites/space_platformer_coin_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_coin_01.png"),
  "sprites/space_platformer_coin_01_collected.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_coin_01_collected.png"),
  "sprites/space_platformer_goal_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_goal_01.png"),
  "sprites/space_platformer_hud_coins_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_hud_coins_01.png"),
  "sprites/space_platformer_hud_lives_01.png": path.resolve(process.cwd(), "../game/sprites/space_platformer_hud_lives_01.png"),
  "sprite-masks/neutral_human_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/neutral_human_01-skin-mask.png"),
  "sprite-masks/neutral_human_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/neutral_human_01-hair-mask.png"),
  "sprite-masks/haunted_human_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/haunted_human_01-skin-mask.png"),
  "sprite-masks/haunted_human_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/haunted_human_01-hair-mask.png"),
  "sprite-masks/space_human_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/space_human_01-skin-mask.png"),
  "sprite-masks/space_human_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/space_human_01-hair-mask.png"),
  "sprite-masks/dragon_human_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/dragon_human_01-skin-mask.png"),
  "sprite-masks/dragon_human_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/dragon_human_01-hair-mask.png"),
  "sprite-masks/neutral_girl_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/neutral_girl_01-skin-mask.png"),
  "sprite-masks/neutral_girl_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/neutral_girl_01-hair-mask.png"),
  "sprite-masks/haunted_girl_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/haunted_girl_01-skin-mask.png"),
  "sprite-masks/haunted_girl_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/haunted_girl_01-hair-mask.png"),
  "sprite-masks/space_girl_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/space_girl_01-skin-mask.png"),
  "sprite-masks/space_girl_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/space_girl_01-hair-mask.png"),
  "sprite-masks/dragon_girl_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/dragon_girl_01-skin-mask.png"),
  "sprite-masks/dragon_girl_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/dragon_girl_01-hair-mask.png"),
  "sprite-masks/ice_world_human_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/ice_world_human_01-skin-mask.png"),
  "sprite-masks/ice_world_human_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/ice_world_human_01-hair-mask.png"),
  "sprite-masks/ice_world_girl_01-skin-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/ice_world_girl_01-skin-mask.png"),
  "sprite-masks/ice_world_girl_01-hair-mask.png": path.resolve(process.cwd(), "../game/sprite-masks/ice_world_girl_01-hair-mask.png"),
};

const CONTENT_TYPES: Record<string, string> = {
  ".png": "image/png",
  ".wav": "audio/wav",
};

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ asset: string[] }> },
) {
  const requestedAsset = (await params).asset.join("/");
  const assetFile = assetFiles[requestedAsset];
  if (!assetFile) {
    return new Response("Game asset not found.", { status: 404 });
  }

  try {
    const file = await readFile(/* turbopackIgnore: true */ assetFile);
    return new Response(new Uint8Array(file), {
      headers: {
        "Cache-Control": "public, max-age=31536000, immutable",
        "Content-Type": CONTENT_TYPES[path.extname(requestedAsset)] ?? "application/octet-stream",
      },
    });
  } catch {
    return new Response("Game asset not found.", { status: 404 });
  }
}
